name: Deploy FAQ API

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
      CDK_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: npm install -g aws-cdk
      - run: cdk bootstrap
      - run: |
          if [[ $GITHUB_REF == 'refs/heads/develop' ]]; then
            cdk deploy FaqDev --require-approval never
          elif [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            cdk deploy FaqProd --require-approval never
          fi
